- src/components/layout/Button.jsx
버튼 컴포넌트 재작
className 속성을 동적으로 생성하여 스타일을 적용하였습니다. 모든 스타일링이 className을 통하여 이루어지도록 tailwindCSS의 클래스를 사용하였습니다. props값에 따라 switch문이 실행되며
필요한 조건에 따라 switch문으로 className을 누적하도록 하였습니다.
**테스트 코드**
```js
import Button from "@components/layout/Button";
export default function Edit() {
return (
<>
<div>
<Button color="red" width="xl" height="sm">
취소
</Button>
<Button color="purple" width="xl" height="sm">
취소
</Button>
<Button color="white" width="xl" height="sm">
취소
</Button>
</div>
<div>
<Button color="purple" width="2xl" height="md">
취소
</Button>
<Button color="white" width="2xl" height="md">
취소
</Button>
<Button color="red" width="2xl" height="md">
취소
</Button>
</div>
<div>
<Button color="white" height="lg">
취소
</Button>
<Button color="purple" height="lg">
취소
</Button>
</div>
<div>
<Button …
```
> [FEAT] Button 공통 컴포넌트 제작

- src/components/layout/InputField.jsx
- src/pages/main/MainList.jsx
**테스트 코드**
```jsx
import InputField from "@components/layout/InputField";
export default function MainList() {
return (
<div>
MainList
<InputField
labelName="생년월일"
type="date"
errorMsg="생년월일 입력은 필수입니다."
/>
<InputField placeholder="기본 텍스트 인풋" />
<InputField labelName="이메일" placeholder="이메일을 입력해 주세요." />
<InputField
labelName="내용"
placeholder="내용을 입력해주세요."
errorMsg="내용 입력은 필수입니다."
isTextArea={true}
isLast={true}
/>
</div>
);
}
```
**테스트 화면**
**Props**
- labelName = "",
: 인풋에 라벨이 있는 경우 text를 넣으면 됩니다.
- type = "text",
: 인풋의 type을 결정합니다.
- placeholder = "",
: 인풋의 placeholder에 해당하는 text를 넣으면 됩니다.
- errorMsg = "",
: error message가 있는 경우 text를 넣으면 됩니다.
- isLast = false,
: 요소들의 아래 마진이 기본적으로 들어가 있기 때문에 isLast를 true로 하면 아래 마진이 제거됩니다.
- isTextArea = false,
: 인풋이 textArea인 경우 true를 주시면 됩니다.
resolves …
> [FEAT] 인풋 컴포넌트 사용

- src/components/layout/Header.jsx
**feat/38-titleHeader** 브랜치 이동 후 확인 해주시면 됩니다.
👉 useMatch를 이용해 페이지별 제목이 적용되게 했습니다.
👉 각자 TitleHeader를 사용하는 페이지를 확인해주세요. 
resolves #38
> [FEAT] TitleHeader 페이지별 title 반영

- src/components/layout/Button.jsx
- [] 새로운 기능 추가
버튼의 width와 같은 추가적인 수치를 직접 설정 가능하도록 하였다.
버튼 색상 조건에 gray를 추가하였다 
버튼의 props의 default값을 추가하였다
- 작동 모습
- 사용 예시 
```js
export default function MainList() {
return (
<>
<Button></Button>
<Button color="gray" className="mb-4 w-full"></Button>
<Button color="red" className="w-11" height="lg"></Button>
<Button color="purple" className="w-[200px]"></Button>
</>
);
}
```
- 추가 사항
```js
export default function Button({
children = "버튼",
onClick,
color = "purple",
height = "sm",
type = "button",
className = "w-full",
})
```
위처럼 props의 default 값을 정의하고 이벤트 함수와 type을 추가적으로 지정 가능하도록 하였다.
className에는 추가로 적용하고 싶은 className을 작성하면 된다 ex)className="mb-4"
resolves #34
> [FEAT] 버튼 컴포넌트 색상 추가 및 width 수정 #34

- src/pages/pr/PRDetail.jsx
> [FEAT] 공고 PR 상세 페이지 UI 작업 완료

- src/pages/pr/PREdit.jsx
> [FEAT] PREdit 수정 페이지 UI 추가

- src/pages/main/MainEdit.jsx
> [FEAT] main 공고 수정 페이지 UI 추가

- public/icons/plus.svg
- src/components/layout/Button.jsx
- src/components/layout/InputField.jsx
- src/index.css
- src/pages/main/MainDetail.jsx
- src/pages/main/MainEdit.jsx
- src/pages/main/MainWrite.jsx
- src/pages/pr/PRDetail.jsx
- src/pages/pr/PRWrite.jsx
- 공고 상세 페이지
사진 추가
-공고 글쓰기 페이지
사진 추가 기능 UI 
-공고 수정 페이지
사진 추가 기능 UI
resolves #61
> [FEAT] main 글쓰기, 수정 페이지에서 사진 추가 UI, 공고 상세 페이지 사진 UI 추가, 아이콘 plus 추가

- src/pages/user/SignIn.jsx
- src/pages/user/SignUp.jsx
**feat/66-userModify 브랜치로 이동 후 확인해주세요**
1. /user/signIn 
👉 에러 메세지와 버튼 간격 mt-5로 수정
👉 페이지 상하 가운데 정렬
2. /user/signUp
👉에러 메세지와 버튼 간격 mt-5로 수정
resolves #66
> [FEAT] user 페이지 수정

- src/index.css
- src/pages/myPage/Likes.jsx
- src/pages/myPage/MyReviews.jsx
- [] CSS 등 사용자 UI 디자인 변경
각 페이지에서 class명이 너무 긴 container box의 className을 커스텀화 했습니다
resolves #71
> [FEAT] myPage의 className custom

- src/components/layout/InputField.jsx
- src/pages/main/MainWrite.jsx
InputComponent에 register과 name props를 추가했습니다.
register: useForm으로부터 받은 register 함수
name: register에 등록할 input 이름
mainWrite.jsx에 테스트 코드를 작성했습니다.
> [FEAT] InputField 컴포넌트 register 연결, 테스트 코드 추가

- src/pages/user/SignIn.jsx
- src/zustand/userStore.js
**❗ 테스트 정보: u1@market.com / 11111111**
이메일 로그인 기능을 구현했습니다. <br><br>
✅ 테스트 내용
로그인에 성공하면 sessionStorage에 userId로 id가 저장되고 메인 페이지로 넘어갑니다.
**2-1) input 필드 미입력**
미입력 된 필드 하단에 에러 메세지가 출력 <br>
👉 이메일: "이메일을 입력해주세요."
👉 비밀번호: "비밀번호를 입력해주세요." <br>
**2-2) input 필드를 입력했는데 실패**
- 이메일/비밀번호가 등록 되어 있지 않는 경우 : 비밀번호 필드 아래 에러 메세지 출력
👉 "이메일과 비밀번호를 확인하세요"
- 이메일 형식에 맞지 않게 작성한 경우: 이메일 필드 아래 에러 메세지 출력
👉 " 이메일 형식으로 작성해주세요"
**3. 회원가입을 클릭하면 /user/terms 로 이동합니다.** <br>
**4. 비밀번호 눈 아이콘 클릭시 보여짐** <br>
✍ 기타
1. InputField를 div가 아닌 form으로 감싸는 것으로 수정했습니다.
2. userStore.js 파일을 추가했습니다.
3. useMutation 을 이용해 구현하였습니다.
resolves #89
> [FEAT] 이메일 로그인 구현

- src/pages/main/MainDetail.jsx
- src/pages/main/MainEdit.jsx
- src/pages/main/MainItem.jsx
- vite.config.js
main 글 수정 페이지
근무 내용에  DOMPurify추가하여 XSS 방지
수정 버튼 누를시 수정, 삭제 기능 추가
confirm으로 구현했으나 추후 변경 예정
디테일 페이지 UI 변경
resolves #101 #106
> [FEAT] main 상세 수정 페이지 

- src/pages/Error.jsx
- src/pages/myPage/Edit.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyReviewList.jsx
- src/pages/myPage/MyReviews.jsx
회원 정보 수정 되는 거랑 myPage에서 Link눌렀을 때 잘 이동하는지 확인해주시면 됩니다.
(프로필 제외)
방법은 user/signIn 에서 들어가고 네오로 로그인한뒤에 해주세요.
resolves #111
> [FEAT]myPage와 관련된 페이지 모두 zustand로 수정(프로필 제외)

- src/index.css
- src/pages/myPage/LikeList.jsx
- src/pages/myPage/Likes.jsx
데이터 화면 뿌리기 //일단은 샘플데이터 값 때문에 extra없는건 '못된고양이'이런 식으로 하드코딩 해놨어요.
지원 클릭하면 글쓰기 페이지 이동
관심글 클릭하면 상세페이지 이동
좋아요 클릭하면 북마크에서 삭제됨, 
alert같은건 리팩토링 할 때 다같이 모양 맞춰서 이쁘게 다듬으면 좋을 거 같아요.
resolves #116
> [FEAT] 관심 리스트 페이지 구현 

- src/pages/myPage/LikeList.jsx
- src/pages/user/Profile.jsx
프로필 페이지 나오도록 설정하였습니다 . 
현재 회원정보 조회 +후기 조회 api를 사용했습니다(2개),  
후기 조회를 사용한 이유는 알바력을 측정하기 위한 별점이 회원 정보 조회에서는 조회가 안되고 후기 조회에서 가능하기 때문입니다. (하지만 후기조회에는 user에 대한 구체적 정보가 없어서 user api를 따로 사용함..)
알바력 빼고  데이터 잘 뿌려지는지, Link 잘 연결되는지 봐주시면 됩니다.
resolves #110
> [FEAT] 프로필 페이지

- src/index.css
- src/pages/Error.jsx
- src/pages/main/MainDetail.jsx
- src/pages/main/MainItem.jsx
- src/pages/main/MainWrite.jsx
- src/pages/myPage/Edit.jsx
- src/pages/myPage/LikeList.jsx
- src/pages/myPage/Likes.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyReviewList.jsx
- src/pages/myPage/MyReviews.jsx
- src/pages/pr/PRWrite.jsx
- src/pages/user/Profile.jsx
PR 글쓰기 페이지 추가
Main 디테일 페이지 UI 변경
resolves #106 #109
> [FEAT] PR 글쓰기 페이지 추가

- src/pages/main/MainDetail.jsx
- src/pages/main/MainItem.jsx
- src/pages/main/MainWrite.jsx
1. 글쓰기 API 변경
<br />
2. 찜하기 기능 추가
<br />
3. 지원하기 버튼
4. 이미지 업로드
resolves #118 #122 #123  #124
> [FEAT] 글쓰기 API 변경, 찜하기 기능 추가, 버튼 비활성화, 이미지 업로드, 더미 데이터 제거

- src/pages/main/ListItem.jsx
- src/pages/main/MainList.jsx
**테스트 페이지**
/main
메인 리스트 페이지에서 반응형 디자인 수정했습니다.
1. 카드 컴포넌트 안에 글자 크기 줄어들게, 이미지 나오게
2. 글쓰기 버튼 사이즈 작아지게
3. 주소 텍스트 작아지게, 아이콘 나오게
수정 필요한 거 있으면 말씀 주세요!
resolves #135
> [FEAT] 메인 리스트 페이지 반응형 레이아웃 수정 

- api/bruno-sample/dda/01.회원/01 회원가입,로그인/판매 회원 로그인(_id=2).bru
- src/hooks/useGetOrderState.js
- src/hooks/useGetOrders.js
- src/hooks/useGetProducts.js
- src/pages/history/Employed.jsx
- src/pages/history/EmployedItem.jsx
- src/pages/history/State.jsx
- src/pages/history/Worked.jsx
- src/pages/history/WorkedItem.jsx
알바 내역 내가 한 일, 내가 시킨 일 페이지 상태 토글 및 필터링 구현 완료했습니다~
**테스트 계정**
1. 내가 한 일 : u1@market.com, 11111111
2. 내가 시킨 일 : s1@market.com, 11111111
**테스트 url**
1. 내가 한 일 : /history
2. 내가 시킨 일 : /history/employed
**테스트 방법**
해당하는 계정으로 로그인 한 후 내가 한 일, 내가 시킨 일 탭에서 상태 토글 버튼(지원 완료, 채택 완료, ...)을 클릭해서 나오는 데이터가 필터링이 됐는지 확인해주시면 됩니다~
resolves #139
> [FEAT] 알바내역 페이지 상태 필터링

- src/hooks/useAxiosInstance.js
- src/pages/user/SignIn.jsx
- useAxiosInstance.js 파일에 토큰 처리를 추가했습니다.
- SignIn.jsx 의 14벝ㄴ째 줄에 "expiresIn: 10s" 를 추가해 accessToken 만료 시간을 10초로 설정했습니다 (삭제 후 머지 예정)
- 토큰 만료 시간을 변경하고 싶으시다면 10s 를 10m ~ 이런식으로 변경하시면 됩니다.
**1. 엑세스 토큰 만료 확인 테스트**
- 엑세스 토큰이 만료되면 로그인으로 갑니다.
✔ 51-54 번째 줄 주석 처리 해제 / 55 - 77 주석 처리 <br> ➡ 로그인 한다 <br> ➡ 유저 정보가 필요한 페이지 (ex. 메인 디테일) 에 들어간다 <br> ➡ 로그인 토큰 만료시 alert 띄움 및 로그인 창 이동<br>
**2. 엑세스 토큰 만료 시 리프레시로 대체 테스트**
- 엑세스 토큰이 만료되면 리프레시 토큰으로 대체됩니다. (로그인 상태가 유지됨)
✔ 로그인 한다 <br> ➡ 유저 정보가 필요한 페이지 (ex. 메인 디테일) 에 들어간다 <br> ➡ 로그인 당시 accessToken과 재발급된 accessToken을 확인한다. (1번: 로그인 시점 2번: 재발급 )<br>
3. 로그인이 되지 않았을때 (72번째 줄~)
- 로그인이 되지 않은 상태면 로그인 페이지로 이동합니다.
최종적으로 적용되는건 2번 입니다.
확인하시면 토큰 만료시간 제거 및 코드 정리 후 머지하겠습니다.
마이페이지 쪽은 아직 미완성입니다. 제외하고 봐주시면 됩니다.
resolves #126
> [FEAT] 토큰 처리

- src/components/layout/Header.jsx
- src/components/layout/index.jsx
- src/hooks/useGetMyProducts.js
- src/hooks/useGetProducts.js
- src/pages/history/Employed.jsx
- src/pages/history/ReviewWrite.jsx
- src/pages/main/MainList.jsx
1. 메인 페이지 레이아웃 수정이 들어갔습니다. (검색 바를 넣기 위해)
2. 메인 페이지 검색 기능을 구현했습니다.
**테스트 방법**
1. / url 접속
2. "기장" 키워드 검색, 결과 하나 나오는 것 확인
3. "카카오" 키워드 검색, 결과 하나 나오는 거 확인
4. 빈 문자열 검색 또는 새로고침 -> 초기화
resolves #
> [FEAT] 메인 페이지 검색

- src/pages/user/SignIn.jsx
- 주석 삭제
- 폰트 rem 적용
- signIn Mutation 한꺼번에 처리
resolves #151
> [FEAT] 로그인 페이지 코드 리팩토링

- src/pages/user/Terms.jsx
> [FEAT] terms 페이지 폰트 수정

- src/pages/history/ReviewWrite.jsx
- src/pages/main/ListItem.jsx
- src/pages/main/MainList.jsx
> 메인, 알바내역, 리뷰 작성 페이지 폰트사이즈 rem으로 수정

- index.html
- package-lock.json
- package.json
- src/components/InputField.jsx
- src/components/layout/Header.jsx
- src/components/layout/index.jsx
- src/hooks/useAxiosInstance.js
- src/hooks/useGetMyProducts.js
- src/hooks/useGetOrders.js
- src/hooks/useGetProducts.js
- src/hooks/useProfileData.js
- src/pages/history/Employed.jsx
- src/pages/history/HistorySarch.jsx
- src/pages/history/ReviewWrite.jsx
- src/pages/history/Worked.jsx
- src/pages/main/ListItem.jsx
- src/pages/main/MainDetail.jsx
- src/pages/main/MainList.jsx
- src/pages/main/MainWrite.jsx
- src/pages/myPage/Likes.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/user/SignIn.jsx
- src/pages/user/Terms.jsx
파일이 너무 꼬여서 다시 브랜치 생성하여 PR 합니다.
글쓰기 버튼 누를 시 confirm으로 환불 관련 내용 
<br />
취소 시
<br />
확인 시
결제 금액은 시급 * 근무 시간으로 계산
resolves #128
> [FEAT] 메인 글쓰기 페이지 결제 시스템 추가 

- src/App.jsx
- src/zustand/splashStore.js
splash을 zustand로 관리하기
resolves #173
> [FEAT] splash zustand로 리팩토링

- routes.jsx
- src/components/layout/Header.jsx
- src/hooks/useGetMyProducts.js
- src/hooks/useGetOrder.js
- src/pages/alarm/Alarm.jsx
- src/pages/history/Employed.jsx
- src/pages/history/EmployedItem.jsx
- src/pages/history/ReviewWrite.jsx
- src/pages/history/WorkedItem.jsx
- src/pages/main/PostList.jsx
- src/pages/main/post/PostDetail.jsx
- src/pages/main/post/PostEdit.jsx
**리팩토링**
알바 내역 내가 시킨 일 페이지에서 product에 있는 worker 값을 이용해서 데이터를 렌더하도록 리팩토링했습니다.
동작은 이전과 동일합니다.
**버그 수정 내역**
알바 내역 내가 시킨 일
- 송금 후 뒤로가기 시 상태 송금완료로 변경
-알람
- 알람 모두 지우기 클릭 시 한 번에 삭제
- 버튼 fixed
메인
- 송금 완료, 리뷰 작성 완료된 글 표시 안 하기
resolves #172
> [BUG] 내가 시킨 일 송금하기 누른 후 데이터 refetch, 기타 버그 수정

- src/pages/main/PostList.jsx
날짜 지난 구인 글 이 메인에 표시되지 않도록 했습니다.
resolves #
> [FEAT] 날짜 지난 구인 글 메인에 안 보이게 하기

- src/pages/history/Employed.jsx
- src/pages/history/Worked.jsx
알바내역 목록 없을 때 텍스트 추가하였습니다.
resolves #188
> [FEAT] 알바내역 목록 없을 때 텍스트 추가

- src/pages/main/post/PostDetail.jsx
- src/pages/main/post/PostPR.jsx
- src/pages/main/post/PostWrite.jsx
날짜에 따라 환불 수수료 각자 적용
input에 띄어쓰기 없이 입력할 경우 튀어나오는 버그 수정
resolves #183 #184
> [FEAT] 날짜에 따른 환불 수수료 적용, input 버그 수정

- src/components/layout/Header.jsx
- src/pages/history/EmployedItem.jsx
- src/pages/history/WorkedItem.jsx
- src/pages/main/post/PostDetail.jsx
알바 내역 상세 보기에서 이동한 디테일 페이지에서 뒤로가기 클릭시 알바 내역으로 이동
resolves #191
> [FEAT] 알바 내역 상세 보기에서 이동한 디테일 페이지에서 뒤로가기 클릭시 알바 내역으로

- routes.jsx
- src/App.jsx
1. route에 지정되지 않은 경로 (ex. /aaa, /bbb) 로 이동했을 때 404 페이지가 나오도록 수정했습니다. (88번째 줄 추가) 
2. App.jsx에서 스크롤 추가
앱 내부가 아닌 전체 스크린에서 스크롤 가능하게 수정
resolves #202
> [REFACTOR] ErrorPage 처리 & 스크롤 바깥에서 하기

- src/pages/history/ReviewWrite.jsx
사장님이 알바생에게 리뷰를 작성할 때 product_id도 함께 전달하도록 했습니다.
resolves #207
> [REFACTOR] 리뷰 작성 시 product_id 전달

- src/pages/user/SignUp.jsx
- src/pages/user/Terms.jsx
1. 약관 페이지
2. 회원가입 페이지 
✅ 초기 버튼은 회색입니다. 
✅ 약관 페이지: 모두 동의가 체크되면 버튼이 보라색으로 변경됩니다.
✅ 회원가입 페이지: 
- 모든 필드가 작성이 되면 버튼이 보라색으로 변경됩니다. 
- 버튼이 활성화 되었는데 유효성 검증에 실패한 경우 기존과 동일하게 에러 메세지가 보여지고 진행되지 않습니다.
resolves #205
> [REFACTOR] 조건부 버튼

- src/pages/main/PostList.jsx
- src/pages/myPage/MyReviewListItem.jsx
- src/pages/myPage/MyReviews.jsx
- src/pages/user/SignUp.jsx
버튼 ui변경과 알바일 때 받은 리뷰 상세 게시글 클릭 시 post게시글로 이동하도록 변경하였습니다
희연님 회원가입 페이지
대따몬 기본 이미지일때는 수정 img이고
이미지 변경했을때는 X로 바꾸도록 추가 수정 했어요
resolves #201
> UI개선 및 버그픽스 해결

- README.md
> [REFACTOR]Update README.md -ver2

- public/icons/x-box.svg
- src/components/layout/Sidebar.jsx
- src/pages/myPage/Edit.jsx
- src/pages/user/Profile.jsx
- src/pages/user/SignUp.jsx
✅ 회원가입과 프로필 수정 ui 통일
(좌: 수정 / 우: 회원가입)
프로필 크기 / border-bottom 통일, x 아이콘과 카메라 아이콘 통일
✅ 유저 페이지 object-cover 잘리는 문제 해결
(좌: 이전 / 우: 수정본)
(기본 이미지일 때 생기는 문제)
✅ 로그인된 상태일때 사이드바에서 프로필 이동 
(형광팬 영역을 클릭하면 프로필 페이지로 이동)
resolves #217
> [REFACTOR] ui 수정

- src/pages/myPage/LikeList.jsx
- src/pages/myPage/Likes.jsx
> [REFACTOR]: 좋아요 목록 순서 변경 및 마감된 게시글 처리

- src/hooks/useGetProducts.js
- src/pages/main/ListItem.jsx
- src/pages/main/PostList.jsx
- src/pages/main/post/PostDetail.jsx
- src/utills/useKakaoLoader.js
- 마감일 지난 글 지원 버튼 비활성화(완료)
- 지원자 중복 지원 불가(진행중)
resolves #222
> [REFACTOR] 마감일 지원 버튼, 지원자 중복 불가

- src/pages/user/SignIn.jsx
카카오 로그인 rest api 를 env에서 관리
VITE_KAKAO_LOGIN_REST_API_KEY = 7b635f7b3d4379252462f78787fc908b
추가
resolves #229
> [REFACTOR] 카카오 로그인 rest api .env 파일로 관리

- src/hooks/useGetProducts.js
- src/pages/main/ListItem.jsx
- src/pages/main/PostList.jsx
홈 페이지에 마감된 게시글을 표시할 지 안 할지 체크할 수 있게 만들었습니다.
마감된 게시글은 마감 필터를 씌워 표시하도록 했습니다.
resolves #227
> [REFACTOR] 홈 페이지 날짜 지난 구인글 마감 처리

- src/pages/main/post/BasicMap.jsx
- src/pages/main/post/PostEdit.jsx
- src/pages/main/post/PostWrite.jsx
- 주소 미입력 시 유효성 실행이 안되는 버그 수정
resolves #231
> [REFACTOR] 주소 미입력 시 글 유효성 활성화 안되는 버그 수정

- src/pages/history/Employed.jsx
- src/pages/history/Worked.jsx
- src/pages/main/PostList.jsx
- src/pages/main/post/PostWrite.jsx
<메인>
관심있는 대타 장소를 검색해보세요 -> 관심있는 공고를 검색해보세요
<리뷰>
내가 일하는 장소를 검색해보세요 -> 내가 지원한 공고를 검색해보세요
나 대신 일하는 사람을 검색해보세요 -> 내가 올린 공고를 검색해보세요
로 수정
resolves #233
> [BUG] placeholder 수정
